// Code generated by "stringer -type=Button -trimprefix=Button"; DO NOT EDIT.

package chimp

import "strconv"

const _Button_name = "PenTipPenEraserPen1Pen2Pen3LeftRightForwardBackTouch"

var _Button_index = [...]uint8{0, 6, 15, 19, 23, 27, 31, 36, 43, 47, 52}

func (i Button) String() string {
	if i >= Button(len(_Button_index)-1) {
		return "Button(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Button_name[_Button_index[i]:_Button_index[i+1]]
}
