// Code generated by "stringer -type=PositionDevice -trimprefix=PositionDevice"; DO NOT EDIT.

package chimp

import "strconv"

const _PositionDevice_name = "PenFinger"

var _PositionDevice_index = [...]uint8{0, 3, 9}

func (i PositionDevice) String() string {
	if i >= PositionDevice(len(_PositionDevice_index)-1) {
		return "PositionDevice(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PositionDevice_name[_PositionDevice_index[i]:_PositionDevice_index[i+1]]
}
